# Generated by Django 3.2.22 on 2023-10-11 21:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cats',
            fields=[
                ('id_cat', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('breed_type', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Não especificado')], default='N', max_length=1)),
                ('rescue_date', models.DateField()),
                ('description', models.TextField()),
                ('is_injured', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True, null=True)),
                ('is_vaccinated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['rescue_date'],
            },
        ),
    ]
